export const names: string[] = [
  "Captain Wobbleknees",
  "Sir Pickletoast",
  "Banana McThunder",
  "Laser Grandpa",
  "Toaster Wizard",
  "Bongo Kraken",
  "Sneaky Meatball",
  "Dr. Waffles",
  "Goblin Refrigerator",
  "Spaghetti Mammoth",
  "Professor Bonk",
  "Chairman Pickles",
  "Fluffy Doom",
  "Turbo Sardine",
  "Noodle Viking",
  "Cactus Bandit",
  "Disco Crocodile",
  "Muffin Destroyer",
  "Beef Supreme",
  "Crusty Nugget",
  "Moon Cheese",
  "Pogo Samurai",
  "Jellybean Titan",
  "Biscuit Phantom",
  "Pancake Barbarian",
  "Gravy Wizard",
  "Sock Pirate",
  "Lemon Volcano",
  "Goose Cannon",
  "Funky Turnip",
  "Milkshake Gladiator",
  "Captain Sniffles",
  "Hamster Tornado",
  "Wiggle Baron",
  "Cosmic Pickaxe",
  "Nuclear Potato",
  "Chicken Overlord",
  "Slippery Crayon",
  "Bubblewrap Ninja",
  "Mustache Lobster",
  "Dizzy Pretzel",
  "Tuna Emperor",
  "Cranky Marshmallow",
  "Frog Zeppelin",
  "Invisible Bacon",
  "Waffle Tank",
  "Turbo Pickle",
  "Ancient Burrito",
  "Beeper McGee",
  "Crab Disco",
  "Flaming Yogurt",
  "The Moist Wizard",
  "Count Spatula",
  "Rubber Duckzilla",
  "Sneezing Dragon",
  "Pudding Knight",
  "Velvet Chainsaw",
  "Captain Oops",
  "Screaming Turntable",
  "Dusty Lasagna",
  "The Flying Meatloaf",
  "Quantum Boot",
  "Grumpy Avocado",
  "Cheese Volcano",
  "Shampoo Bandit",
  "Feral Cupcake",
  "The Screeching Walnut",
  "Microwave Cowboy",
  "Frostbite Pickle",
  "King Noodles",
  "Angry Pajamas",
  "The Banjo Reaper",
  "Spicy Refrigerator",
  "Criminal Pancake",
  "Tactical Grandma",
  "Moldy Hotdog",
  "Captain Sidequest",
  "Funky Blender",
  "Soup Goblin",
  "Bearded Crumpet",
  "The Sock Whisperer",
  "Rotisserie Ninja",
  "Dr. Soggy",
  "The Haunted Meatball",
  "Butterlord Supreme",
  "Turbo Grandpa",
  "Cereal Assassin",
  "The Crispy Oracle",
  "Electric Mustard",
  "Gremlin Cowboy",
  "Pineapple Destroyer",
  "The Bouncing Walrus",
  "Salsa Viking",
  "Goblin Tax Collector",
  "Wormzilla",
  "Suspicious Muffin",
  "Captain Toenail",
  "Robo Pickles",
  "The Yodeling Sausage",
  "Breadstick Phantom",
  "Mega Chimp Supreme",
  "The Honking Wizard"
];